# Welcome to Jekyll!
#

# Site settings
title: Terres de Bord Ensemble
description: |
  Une équipe compétente pour notre commune, ensemble
owner: Terres de Bord Ensemble # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: tdb.ensemble@free.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  # github: https://github.com/<username>
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  email: tdb.ensemble@free.fr

  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:
collections:
  team:
    output: false
  propositions:
    output: true
# Build settings
markdown: kramdown
#sass:
#  style: compressed
