backend:
  name : github
  repo : lejedi76/lejedi76.github.io
  commit_messages:
    create: Ajout {{collection}} “{{slug}}”
    update: Mise à jour {{collection}} “{{slug}}”
    delete: Suppression {{collection}} “{{slug}}”
    uploadMedia: Téléversement “{{path}}”
    deleteMedia: Suppression “{{path}}”
  # name: git-gateway
  # branch: master # Branch to update (optional; defaults to master)

media_folder: "images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "membre" # Used in routes, e.g., /admin/collections/blog
    label: "Membre de l'équipe" # Used in the UI
    description: "Ajouter un membre à l'équipe"
    identifier_field: name
    folder: "_team" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Nom", name: "nom", widget: "string"}
      - {label: "Prénom", name: "prenom", widget: "string"}
      - {label: "Age", name: "age", widget: "number", min:18, max:130}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Métier", name: "metier", widget: "string"}
      - {label: "Lieu-dit", name: "lieu-dit", widget: "select", options: ["Montaure", "Ecrosville", "Tostes", "Les Fosses"]}
      - {label: "Motivation", name: "motivation", widget: "markdown"}
